apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: example/nginx
  name: nginx
  labels:
    package-instance: nginx
  namespace: nginx
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|example|nginx'
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      package-instance: nginx
  template:
    metadata:
      labels:
        package-instance: nginx
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: nginx
        image: nginx:stable-perl
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        args: ["-conf", "/etc/coredns/Corefile"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
          readOnly: true
        ports:
        - containerPort: 80
          name: nginx
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
      dnsPolicy: Default
      volumes:
      - name: config-volume
        configMap:
          name: nginx-file
          items:
          - key: Corefile
            path: Corefile
