apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: example/nginx
  name: nginx
  labels:
    package-instance: nginx
  namespace: nginx
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|example|nginx'
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  selector:
    matchLabels:
      package-instance: nginx
  template:
    metadata:
      labels:
        package-instance: nginx
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: nginx
        image: nginx:stable-perl
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 300Mi
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
