apiVersion: v1
kind: Service
metadata: # kpt-merge: example/nginx
  name: nginx
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
    internal.kpt.dev/upstream-identifier: '|Service|example|nginx'
  labels:
    package-instance: nginx
  namespace: nginx
spec:
  selector:
    package-instance: nginx
  ports:
  - name: nginx
    port: 80
    protocol: TCP
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: metrics
    port: 9153
    protocol: TCP
