apiVersion: v1
kind: Service
metadata: # kpt-merge: example/nginx
  name: nginx
  labels:
    package-instance: nginx
  namespace: example
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|example|nginx'
spec:
  selector:
    package-instance: nginx
  ports:
  - name: nginx
    port: 80
    protocol: TCP
